from typing import Any, Protocol


class StorageProvider(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> None: ...
    async def get(self, key: str) -> tuple[bytes, str]: ...
    async def delete(self, key: str) -> None: ...


class AIProvider(Protocol):
    async def complete(self, *, system: str, prompt: str) -> str: ...


class EmailProvider(Protocol):
    async def send(self, *, to: str, subject: str, text: str) -> None: ...


class IntervalsProvider(Protocol):
    def activities(self, *, api_key: str, athlete_id: str, oldest: str, newest: str) -> list[dict]: ...


class MLProvider(Protocol):
    async def status(self) -> dict: ...
    async def retrain(self, *, model: str) -> dict: ...
    async def overtraining_risk(self, *, user_id: str, as_of: str | None = None) -> dict: ...
    async def anomalies(self, *, user_id: str, activity_type: str | None = None) -> dict: ...
    async def race_prediction(self, *, user_id: str, **kwargs: Any) -> dict: ...


class PaymentProvider(Protocol):
    async def create_connect_account(
        self, *, email: str, country: str, metadata: dict
    ) -> dict: ...

    async def create_account_link(
        self, *, account_id: str, refresh_url: str, return_url: str
    ) -> dict: ...

    async def create_checkout_session(
        self, *, account_id: str, amount_cents: int, currency: str,
        description: str, metadata: dict, commission_percent: int,
        success_url: str, cancel_url: str,
    ) -> dict: ...

    async def retrieve_checkout_session(self, *, session_id: str) -> dict: ...

    async def create_refund(
        self, *, payment_intent_id: str,
        amount_cents: int | None = None, reason: str = "",
    ) -> dict: ...

    def construct_webhook_event(
        self, *, payload: bytes, sig_header: str
    ) -> dict: ...
